name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.13", "3.10.5"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -e .[dev]
    - name: Execute Unit Tests
      run: |
        python -m pytest
    - name: Run csvtofhir CLI
      run: |
        csvtofhir validate -f demo/config/data-contract.json
        csvtofhir convert -f demo/input/Patient.csv -c demo/config  -o demo/output
        rm -rf demo/output
        mkdir -p demo/output
        csvtofhir convert -d demo  -o demo/output
